<h1 style="text-align: center">
<div style="color: #DD3403; font-size: 60%">Data Science DISCOVERY MicroProject</div>
<span style="">MicroProject #7: Creating an Image Mosaic</span>
<div style="font-size: 60%;"><a href="https://discovery.cs.illinois.edu/microproject/creating-an-image-mosaic/">https://discovery.cs.illinois.edu/microproject/creating-an-image-mosaic/</a></div>
</h1>

<hr style="color: #DD3403;">

## Prerequisite: Understanding of Image Mosaics and Terminology

This MicroProject assumes that you understands what an image mosaic is and the terminology of a **base image** and **tile images**.  If you have not done so yet, make sure to read the full MicroProject introduction on the DISCOVERY website here: 
- [https://discovery.cs.illinois.edu/microproject/creating-an-image-mosaic/](https://discovery.cs.illinois.edu/microproject/creating-an-image-mosaic/)

Once you're ready, let's nerd out in creating your own mosaic! 🎉

<hr style="color: #DD3403;">

## Section 1: Loading the DISCOVERY Library

To access an image as a DataFrame, we have provided the DISCOVERY library to help process the image into a DataFrame.  This provided code is in the `lib` directory in your MicroProject.

Specifically, the function we provided is `DISCOVERY.loadImageAsDataFrame("sample.png")`, which loads an image and returns the image's pixel data as a DataFrame.

To use this function:

- First, import DISCOVERY by using `from lib import DISCOVERY` (all caps, because DISCOVERY!)
- Then, `image = DISCOVERY.loadImageAsDataFrame("sample.png")` to load the `sample.png` image into a DataFrame named `image`
- FInally, type `image` as the last line in the cell to display the contents of the DataFrame you just created

Try that out in the cell below:

In [4]:
from lib import DISCOVERY 

image= DISCOVERY.loadImageAsDataFrame("sample.png")
image

   x  y    r    g    b
0  0  0    0    0  255
1  0  1    0  255    0
2  0  2  255  255  255
3  1  0  255  255  255
4  1  1    0    0    0
5  1  2  255   85   46
6  2  0  255    0    0
7  2  1  255  255  255
8  2  2   19   41   75

### Finding a Single Pixel

In the cell below, select the row with the GREEN 🟩 pixel (second row, first column) and store it in the variable `green_pixel`:

In [18]:
green_pixel = image[((image['r'] == 0) & (image['g'] == 255) & (image['b'] == 0))]
green_pixel

   x  y  r    g  b
1  0  1  0  255  0

In [19]:
### TEST CASE for Section 1: Loading the DISCOVERY Library
from lib import DISCOVERY
DISCOVERY.run_test_case_1b(green_pixel)

✅ `green_pixel` contains just one pixel!
✅ `green_pixel` is a green pixel!
🎉 All tests passed! 🎉

<hr style="color: #DD3403;">

## Section 2: Accessing Color Data

Every color visible on a computer screen is made up of the three **primary colors of light** -- red, green, and blue.  Your monitor displays color by varying the intensity of the red light, green light, and blue light emitted for every pixel on your screen.  Since images are primary displayed on computer screens, the **default "color space" is to represent colors as red, green, and blue**.

When you have a pixel, you will always see the three components.  For example, the contents of `green_pixel` is `[0, 255, 0]`:
- The first `0` means we have 0 / 255 (0%) **red** light
- The second `255` means we have 255 / 255 (100%) **green** light
- The final `0` means we have 0 / 255 (0%) **blue** light

### Section 2.1: Accessing Illini Orange

Using the `image` you loaded in Section 1, create a DataFrame that contains **ONLY** the three pixels on the top row of the DataFrame.  Store that subset of the DataFrame in the variable `image_topRowSubset`:

In [46]:
image_topRowSubset = image.iloc[0:3]
image_topRowSubset

   x  y    r    g    b
0  0  0    0    0  255
1  0  1    0  255    0
2  0  2  255  255  255

The top row should contain only three pixels.  Check your DataFrame to make sure that you have only:
- A **blue pixel**, where `b = 255` and both `r = 0` and `g = 0`.
- A **red pixel**, where `r = 255` and both `g = 0` and `b = 0`.
- A **white pixel**, where `r`, `g`, and `b` are all `255`.

Once we have a subset, we can use our DataFrame operations on our subset.   For example, let's look at the **median** value for each color.
- The red components of the three pixels is `[0, 255, 255]`.  This means the **median** red value should be `255`.
- However, the green components of the three pixels is `[0, 0, 255]`.  This means the **median** red value should be `0`.

Calculate the median r, g, and b values of the `image_topRowSubset` image below:

*(Hint: You can find the median of a DataFrame column with the `.median()` function on the DataFrame's column data.)*

In [51]:
r_median = image_topRowSubset['r'].median()
r_median

np.float64(0.0)

In [48]:
g_median = green_pixel['g'].median()
g_median

np.float64(255.0)

In [49]:
b_median = image_topRowSubset['b'].median()
b_median

np.float64(255.0)

In [50]:
### TEST CASE for Section 2: Accessing Color Data
DISCOVERY.run_test_case_2(r_median, g_median, b_median)

✅ `r_median` is a number!
❌ `r_median` is not the correct value.  (Did you use only the image subset of only the top row?)

<hr style="color: #DD3403;">

## Section 3: Finding the Average Color of the Sample Image

Now, find the **average color** (*not the median anymore!*) of the **entire** `image` by finding `r_avg`, `g_avg`, and `b_avg`:

In [0]:
r_avg = ...
r_avg

In [0]:
g_avg = ...
g_avg

In [0]:
b_avg = ...
b_avg

<hr style="color: #DD3403;">

## Section 4: Find the Average Color of ANY Image

Building off Section 3, we now want to find the average color of **ANY** image.  To do that, we need to create a function that is given a DataFrame `image` and returns the average color of that image.

Write this in the function `findAverageColor` below.  You must return the **average color as a dictionary** with the values:
- `r_avg`, for the average red color,
- `g_avg`, for the average green color,
- `b_avg`, for the average blue color

A **dictionary** is a data structure that stores multiple values.  You have used a dictionary in "Step 4" of your simulation code, where you use `d` to accumulate all real-world values.  Accumulate the values `r_avg`, `g_avg`, and `b_avg` just like you would in the simulation:

---
```py
def findAverageImageColor(image):
  ...

  # Return a dictionary of average color:
  d = {"r_avg" : r_avg, "g_avg": g_avg, "b_avg": b_avg}
  return d
```
---

Write the entire `findAverageImageColor` function to find the average color of the `image` passed into the function:

In [0]:
def findAverageImageColor(image):
  ...

In [0]:
### TEST CASE for Section 4: Find the Average Color of ANY Image
DISCOVERY.run_test_case_4(findAverageImageColor)

<hr style="color: #DD3403;">

## Section 5: Dividing Your Base Image Into Small Grid Tiles

To create a mosaic from an image, we must split the base image into small regions to be replaced with the tile images. To accomplish this, we need a function that will **find the subset of pixels found in a region of an image**.

- Thinking about Section 2, you found the subset of the image that included **all pixels in the top row**.
- Other subsets of the sample `sample.png` 3x3 pixel image might be a 2x2 square of pixels, or a a 1x3 rectangle, or any number of other subsets.

Since we might need any rectangular region of an image, lets create a function that returns a rectangular region on an input image that starts at (`x0`, `y0`) and spans `width` pixels wide and `height` pixels tall.


### Your `findImageSubset` function

Specifically, create a function `findImageSubset` that finds the subset of the image starting at (`x0`, `y0`), spanning `width` pixels wide and `height` pixels tall. Your function must return the **subset of all the pixels in that region of the image**.

- Example: `findImageSubset(image, x0=0, y0=0, width=3, height=3)` -- returns subset of all the pixels in the square defined by: x=0...2 and y=0...2 (9 total pixels)

- Example: `findImageSubset(image, x0=5, y0=5, width=5, height=5)` -- returns subset of all the pixels in the square defined by: x=5...9 and y=5...9 (25 total pixels)

- Example: `findImageSubset(image, x0=5, y0=0, width=5, height=5)` -- returns subset of all the pixels in the square defined by: x=5...9 and y=0...4 (25 total pixels)

- Example: `findImageSubset(image, x0=15, y0=0, width=5, height=10)` -- returns subset of all the pixels in the square defined by: x=15...19 and y=0...9 (50 total pixels)

In [0]:
def findImageSubset(image, x0, y0, width, height):
  ...

In [0]:
### TEST CASE for Section 5: Dividing Your Base Image Into Small Grid Tiles
DISCOVERY.run_test_case_5(findImageSubset)

<hr style="color: #DD3403;">

## Section 6: Finding the Average Color of a Subset

You have created two functions:

1. A function that finds the average color of a DataFrame of pixels (`findAverageImageColor`), **AND**
2. A function that finds a subset of pixels of an image (`findImageSubset`)

Create a new function, `findAverageImageSubsetColor` that combines both of them and returns the average color of a subset of the image:

In [0]:
def findAverageImageSubsetColor(image, x0, y0, width, height):
  # Find the subset:
  ...

  # Find and return the average color of the subset:
  ...

In [0]:
### TEST CASE for Section 6: Finding the Average Color of a Subset
DISCOVERY.run_test_case_6(findAverageImageSubsetColor)

<hr style="color: #DD3403;">

## Section 7: Finding the Average Color of Your Tile Images

To create an image mosaic, we need to find the average pixel color of every one of our tile images so that you can find the **best tile image** to use when you're creating your mosaic.  The code below is already complete and does the following:

- Goes through each image file in your `path` directory,
- Finds the average pixel color of each image using your `findAverageColor` function from Section 4,
- Finally, creates a new DataFrame `df_tiles` with the average color of each image and returns that DataFrame.

*Make sure to run this code -- we'll use it in the very next section!*

In [0]:
import pandas as pd

def createTilesDataFrame(pathOrList):
  data = []

  # If the data is a list, use the list of files; otherwise use the path:
  if type(pathOrList) is list:
    fileNames = pathOrList
  else:
    fileNames = DISCOVERY.listTileImagesInPath(pathOrList)

  # Loop through all images in the `path` directory:
  for tileImageFileName in fileNames:
    # Load the image as a DataFrame and find the average color:
    image = DISCOVERY.loadImageAsDataFrame(tileImageFileName)
    averageColor = findAverageImageColor(image)

    # Store the fileName and average colors in a dictionary:
    d = { "fileName": tileImageFileName, "r": averageColor["r_avg"], "g": averageColor["g_avg"], "b": averageColor["b_avg"] }
    data.append(d)

  # Create the `df_tiles` DataFrame:
  df_tiles = pd.DataFrame(data)
  return df_tiles

## Understand the Output

Here's the DataFrame output that the function creates for some sample images.  The DataFrame has four columns:
- `fileName`, containing the name of the tile image
- `r`, `g`, and `b`, containing the average color for the image

We will use this on your tile images directory when we put this all together to make your mosaic, but since that will contain hundreds of images we're going to start with just two sample images:

In [0]:
createTilesDataFrame(["sample.png", "sample2.png"])

<hr style="color: #DD3403;">

## Section 8: Finding the Best Match

There's just one last function to create before we can start making mosaics!  This function needs to find the best tile for a given average color.

To do this, your function will use two pieces of data:

1. Your function will use the DataFrame that contains all of the tile images.  This will be the DataFrame form Section 7, `df_tiles`, and contains the tile image filename and each tile's `r`, `g`, and `b` average pixel colors.
2. Your function will be called with the **average color of the current region of your base image that you're searching for a tile image to replace**.  The color of the base image is passed into your function as `r_avg`, `g_avg`, and `b_avg`.

Using this DataFrame of all tile images and the (`r_avg`, `g_avg`, and `b_avg`) form the base image, create the `findBestTile` that must **find the best tile image from `df_tiles` for a given average color**.  You should do this by finding the single row in `df_tiles` that has the smallest distance from the average color.

### Example 

Imagine you just have three tiles, so your `df_tiles` DataFrame is:

| fileName | r | g | b |
| -------- | - | - | - |
| ./red.jpg | 255 | 0 | 0 |
| ./green.jpg | 0 | 255 | 0 |
| ./blue.jpg | 0 | 0 | 255 |


If your image subset has `r_avg` = 10, `g_avg` = 200, and `b_avg` = 20, we can use the distance formula (Pythagorean's Theorem) to find how "far away" the average color is from each of the tile images:

1. For the red tile (255, 0, 0), the distance away is $d = \sqrt{(255 - 10)^2 + (0 - 200)^2  + (0 - 20)^2} = 316.8990375$
2. For the green tile (0, 255, 0), the distance away is $d = \sqrt{(0 - 10)^2 + (255 - 200)^2  + (0 - 20)^2} = 59.37171044$
3. For the blue tile (0, 0, 255), the distance away is $d = \sqrt{(0 - 10)^2 + (0 - 200)^2  + (255 - 20)^2} = 308.7474696$

We find that the green tile is the closest since it has the minimum distance.  The green tile should be returned.


### Hints

- It will be **VERY** helpful to add an extra column to your DataFrame -- like `df["distance"] = ...`.
- Once you have the distance calculated, how do you return just the smallest row?

In [0]:
def findBestTile(df_tiles, r_avg, g_avg, b_avg):
  ...

In [0]:
### TEST CASE for Section 8: Finding the Best Match
DISCOVERY.run_test_case_8(findBestTile)

<hr style="color: #DD3403;">

## Section 9: Create Your Mosaic!

Time to put everything together!

- Make absolutely certain you have **saved this notebook**.  The next part will import this notebook as the initial work.
- Once this notebook has been saved, open `part2-create-mosaic.ipynb` to continue this project.